Php issue 7
Tazya/kolesa-upgrade-delivery-adm pull request #9
Opened 2022-11-16 19:33 UTC by MarkhabatSansyzbay

Насчет части парсинга конфиг файла неуверена, где лучше было это сделать. Скажете, где исправить:)

2022-11-17 08:59 UTC, Koala610 requested changes

2022-11-17 08:59 UTC, Koala610 commented on src/Http/Controllers/MessageController.php
>          }
Создание сообщения через репозиторий надо после проверки на наличие ошибок поставить, чтобы создавалось только валидное сообщение.

2022-11-17 12:50 UTC, MarkhabatSansyzbay commented on src/Http/Controllers/MessageController.php
>          }
ой точно. спасибо, исправлю

2022-11-17 14:38 UTC, Koala610 approved these changes

2022-11-18 11:26 UTC, Tazya approved these changes
Всё хорошо, ты молодец, но дождемся релиза задачи Владлена
- #8

2022-11-20 16:44 UTC, merged